version: '3.4'

services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
    volumes: 
      - eventstore-data:/var/lib/eventstore
    ports:
      - 1113:1113
      - 2113:2113
  mongo:
    image: mongo:4.0.0-rc0-xenial
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbit:/var/lib/rabbitmq
volumes:
  redis-data:
  mongo-data:
  eventstore-data:
  rabbit: